fixed a bug
TypeError: FileSaver vue__WEBPACK_IMPORTED_MODULE_5__ default.a.saveAs is not a function
This bug is caused by FileSaver npm package is empty.